driver service tests
nostrumee/cab-aggregaror pull request #12
Opened 2023-12-19 14:58 UTC by nostrumee

add unit, integration and component tests for driver-service

2023-12-21 09:24 UTC, KirillKostylev commented on driver-service/src/test/java/com/modsen/driverservice/component/step/DriverServiceStepDefinitions.java
> +        this.driverRepository = mock(DriverRepository.class);
У тебя cucumber для модульных или интеграционных тестов?

2023-12-21 09:29 UTC, nostrumee commented on driver-service/src/test/java/com/modsen/driverservice/component/step/DriverServiceStepDefinitions.java
> +        this.driverRepository = mock(DriverRepository.class);
Для модульных. Советовался с Максимом, решили что оба подхода применимы, поэтому решил делать для модульных и мокать все, а не использовать реальную базу данных. В других микросервисах так же делаю

2023-12-21 12:20 UTC, KirillKostylev commented on driver-service/src/test/java/com/modsen/driverservice/component/step/DriverServiceStepDefinitions.java
> +        this.driverRepository = mock(DriverRepository.class);
* Как по мне, немного избыточно для модульных тестов. А фича файлы особенно удобны для тестеров, кто не особо разбирается в коде (часто именно они составляют эти файли для разрабов), поэтому и удобно использовать их для проверки всего приложения.  И тут вопрос, нужно ли такое описание для разрабов? (если этот момент оговорен то ок, я просто о таком подходе не слышал, вот и интересно)
* Получается у тебя 2 реализации модульных тестов(с кукумбер и с мокито). Какой код чем тестить? или тестить один сервис дважды (как я понял, твой варик). Выглядит избыточно. Можно оставить что-то одно

2023-12-21 12:24 UTC, KirillKostylev commented on driver-service/src/test/java/com/modsen/driverservice/service/impl/RideServiceOrderImplTest.java
> +    }
Есть еще подход с [AAA pattern](https://java-design-patterns.com/patterns/arrange-act-assert/), можешь добавить, много времени не займет

2023-12-21 12:45 UTC, nostrumee commented on driver-service/src/test/java/com/modsen/driverservice/component/step/DriverServiceStepDefinitions.java
> +        this.driverRepository = mock(DriverRepository.class);
Получается что так, но такой подход был оговорен, типо чтобы просто попробовать руками Cucumber. А все приложение я буду тестировать в end-to-end тестировании, там тоже cucumber будем использовать

2023-12-21 12:46 UTC, nostrumee commented on driver-service/src/test/java/com/modsen/driverservice/service/impl/RideServiceOrderImplTest.java
> +    }
А можешь подробнее объяснить? Просто я и старался придерживаться его: сначала делаю сетап, потом вызываю тестируемый метод, потом проверяю ассерты и то были ли вызваны необходимые методы

2023-12-21 12:50 UTC, KirillKostylev commented on driver-service/src/test/java/com/modsen/driverservice/service/impl/RideServiceOrderImplTest.java
> +    }
Да, все так, просто раздели еще комментариями, чтобы сходу было видно где-что

![image](https://github.com/nostrumee/cab-aggregaror/assets/37846646/3d2ce7de-ddbb-4b02-bcc5-795abefc95d2)

2023-12-21 18:29 UTC, nostrumee commented on driver-service/src/test/java/com/modsen/driverservice/service/impl/RideServiceOrderImplTest.java
> +    }
Добавил. Есть вопрос, надо ли в интеграционные тесты такое добавлять? Просто я прочитал что такое принято обычно именно для юнит тестов

2023-12-22 15:05 UTC, KirillKostylev commented on driver-service/src/test/java/com/modsen/driverservice/service/impl/RideServiceOrderImplTest.java
> +    }
Да обычно  для юнит тестов

2023-12-22 15:07 UTC, nostrumee commented on driver-service/src/test/java/com/modsen/driverservice/service/impl/RideServiceOrderImplTest.java
> +    }
Можно мержить?

2023-12-22 15:21 UTC, KirillKostylev requested changes
Хотел отписать рекомендацию перед апрувом, но нашел до чего бы еще докапаться, сорян)))

2023-12-22 15:21 UTC, KirillKostylev commented on driver-service/src/test/java/com/modsen/driverservice/integration/kafka/RideFunctionsIntegrationTest.java
> +        kafka.start();
Эту часть лучше вынести в TestcontainersBase, у тебя же может быть несколько сервисов для тестирования. И они будут наследоваться TestcontainersBase, чтобы не поднимать это несколько раз

2023-12-22 15:21 UTC, KirillKostylev commented on driver-service/src/test/java/com/modsen/driverservice/integration/kafka/RideFunctionsIntegrationTest.java
> +    }
Тоже общая логика для TestcontainersBase

2023-12-22 15:21 UTC, KirillKostylev commented on driver-service/src/test/java/com/modsen/driverservice/util/TestUtils.java
> +    public final String DELETE_DRIVER_PATH = "/api/v1/drivers/{id}";
константы для путей можно переиспользовать (в контроллерах и в тестах)
Если кто-то версию или путь поменяет, может не знать, что еще и тесты надо редачить

2023-12-22 15:21 UTC, KirillKostylev commented on driver-service/src/test/java/com/modsen/driverservice/util/TestUtils.java
> +    public final String CREATE_RIDE_TOPIC_NAME = "create-ride-topic";
в целом ок, но часто выносят в конфиги имена топиков

2023-12-22 15:21 UTC, KirillKostylev commented on driver-service/src/test/java/com/modsen/driverservice/util/TestUtils.java
> +    public final String KAFKA_IMAGE_NAME = "confluentinc/cp-kafka:7.3.3";
это тоже можно в конфиги вынести

2023-12-22 15:21 UTC, KirillKostylev commented on driver-service/src/test/java/com/modsen/driverservice/integration/kafka/RideFunctionsIntegrationTest.java
> +public class RideFunctionsIntegrationTest extends TestcontainersBase {
Рекомендую для одного из микросервисов интеграционные тесты написать с использованием mockMVC (часто используется в проектах)

2023-12-25 15:20 UTC, nostrumee commented on driver-service/src/test/java/com/modsen/driverservice/integration/kafka/RideFunctionsIntegrationTest.java
> +    }
Возникли проблемы с тем чтобы вынести это в общий класс, потому что тогда на все классы будет использоваться один consumer и producer, и если их закрыть то в следующем классе с ними уже нельзя будет работать. Пытался гуглить насколько критично их закрывать, но не смог найти толковой информации. Но они мне и не нужны во всех классах, поэтому возможно не так критично что они не в общем классе, а использую их по необходимости в тестовых классах для кафки

2023-12-25 15:26 UTC, nostrumee commented on driver-service/src/test/java/com/modsen/driverservice/util/TestUtils.java
> +    public final String CREATE_RIDE_TOPIC_NAME = "create-ride-topic";
Дело в том что они у меня есть в проперти файле и  в проекте я использую @ConfigurationProperties файл для доступа к этим пропертям. Но в тестах они мне нужны в статик контексте, и вот тут возникают проблемы ) Не смог найти какого-то хорошего решения для инжекта пропертей в статические поля. и в целом пишут что это не рекомендуется делать. И если нужно именно какие-то статические константы то допускается объявлять их как static final в ютилити классах. Я пришел к одному решению (файл PropertiesUtil), но в нем есть недостаток - он привязан к одному имени файла application.yml, поэтому проперти всегда будут браться оттуда, даже если с другим профилем запущено приложение.
Все это относится и к именам докер образов. Так что буду рад если подскажешь как тут лучше поступить, либо вообще лучше вернуть как было )

2023-12-26 09:48 UTC, KirillKostylev commented on driver-service/src/test/java/com/modsen/driverservice/integration/kafka/RideFunctionsIntegrationTest.java
> +    }
Думаю это должно быть ок. Если у тебя будет несколько продьюсеров и консьюмеров в одном классе (не думаю, что в рамках одного микросервиса у тебя будет много топиков, хотя я тут хз)))

Как я вижу эту проблему, если у тебя будет много классов, где ты поднимаешь контейнеры для каждого - это время выполнения тестов, поэтому было бы идеально один раз поднять -> прогнать тесты -> стопнуть

2023-12-26 10:00 UTC, nostrumee commented on driver-service/src/test/java/com/modsen/driverservice/integration/kafka/RideFunctionsIntegrationTest.java
> +    }
Так тестконтейнеры я пофиксил как ты предлагал) Сейчас у меня все тесты переиспользуют одни и те же тестконтейнеры, то есть они поднимаются один раз перед всеми интеграционными тестами
А producer и consumer это инстансы KafkaProducer и KafkaConsumer, которые я использую чтобы протестировать кафка топики, к тестконтейнерам они отношения не имеют, и их я не могу вынести в общий класс, потому что после первого класса сработает закрытие ресурсов и во втором классе я уже не смогу их использовать. А так у меня в каждом классе свой продьюсер и консьюмер (там где они нужны), и закрываю я их в том классе где использовал.

2023-12-26 10:03 UTC, KirillKostylev commented on driver-service/src/test/java/com/modsen/driverservice/integration/kafka/RideFunctionsIntegrationTest.java
> +    }
Все, вижу)

2023-12-26 10:11 UTC, KirillKostylev approved these changes

2023-12-26 10:41 UTC, merged