metrics observability
nostrumee/cab-aggregaror pull request #18
Opened 2024-01-12 09:36 UTC by nostrumee

add prometheus and grafana support

2024-01-16 00:05 UTC, AbandonedScope requested changes

2024-01-16 00:05 UTC, AbandonedScope commented on observability/prometheus/prometheus.yml
Смотрел как их динамически находит (в случае, когда например несколько инстансов одного и того же сервиса запускать)?

2024-01-16 06:52 UTC, nostrumee commented on observability/prometheus/prometheus.yml
Неа, не проверял, посмотрю сегодня

2024-01-22 16:51 UTC, AbandonedScope approved these changes

2024-01-22 18:28 UTC, merged